steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/basic-security-2/basic-security:$SHORT_SHA', '.']
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['beta', 'run', 'deploy', 'basic-security',  '--region=us-central1', '--platform=managed', '--image=gcr.io/basic-security-2/basic-security:$SHORT_SHA']


    